In [1]:
import os
import sys
import time

sys.path.insert(0, './..')
import analyse_utils
import numpy as np
import os
from svcca import cca_core, pwcca
import importlib

importlib.reload(pwcca)
importlib.reload(analyse_utils)
importlib.reload(cca_core)
import json
from datetime import datetime
import sklearn.metrics
import argparse

In [25]:
import scipy.spatial

In [63]:
X=np.random.rand(10,1000)
Y=np.random.rand(30,1000)

In [67]:
analyse_utils.linear_CKA(X.T,X.T)

0.9999999999999998

In [88]:
(X@X.T).mean(axis=0)

array([258.36939858, 256.67616436, 254.36932245, 265.46787603,
       259.04670694, 257.84826127, 253.47688804, 261.48076227,
       262.28849928, 257.01222884])

In [90]:
centering(X@X.T).mean(axis=1)

array([-0.23421223, -1.92744645, -4.23428835,  6.86426523,  0.44309613,
       -0.75534954, -5.12672277,  2.87715146,  3.68488848, -1.59138196])

In [99]:
def centering(K):
    n = K.shape[0]
    unit = np.ones([n, n])
    I = np.eye(n)
    H = I - unit / n
    print(H)
    print(K)
    print(H@K)
    return np.dot(np.dot(H, K),H)
  # HKH are the same with KH, KH is the first centering, H(KH) do the second time, results are the sme with one time centering


In [2]:
X=np.asarray([[1,3],[2,4]])

In [4]:
Z=X.T@X

In [5]:
np.sum(Z@Z)

1552

In [7]:
np.sum(Z)*np.sum(Z)

2704

In [38]:
start=time.time()
for i in range(6400):
    1-scipy.spatial.distance.cosine(a,b)
print(time.time()-start)

0.4690265655517578


In [39]:
start=time.time()
for i in range(6400):
    sklearn.metrics.pairwise.cosine_similarity([a],[b])[0,0]
print(time.time()-start)

2.2479186058044434


In [20]:
sklearn.metrics.pairwise.cosine_similarity(X,Y)

array([[0.96989225, 0.99570197, 0.99608149, 0.96137289],
       [0.70461104, 0.90037532, 0.89854331, 0.68093178],
       [0.99714118, 0.91536225, 0.91704213, 0.99908454],
       [0.95461685, 0.99934011, 0.9994836 , 0.94432272]])

In [30]:


def store_json(data, filename):
    f = open(filename, 'w', encoding='utf-8')
    json.dump(data, f, indent=4)


def sec_to_string(seconds):
    minutes = int(seconds / 60)
    hours = int(minutes / 60)
    seconds = seconds % 60
    minutes = minutes % 60
    return "{0:02d}:{1:02d}:{2:02d}".format(int(hours), int(minutes), int(seconds))



sim_cal_func="pwcca"


model_paths = ["../.."]
model_names = ["RRAIL"]
# inner_steps=args.inner_steps
data_directionary = "./"
inclusive_layer_sim_analyse=False
exclusive_layer_sim_analyse=False
verbose = False

# labels=np.load("labels_analyse.npz",allow_pickle=True)["arr_0"]
# model_names=["MAML","ANIL","RRAIL"]
# inner_steps=10
# data_directionary="./json_data"
# verbose=False

data_directionary = data_directionary + "/" + datetime.now().strftime("%d%m%y_%H%M%S") + "/"
os.makedirs(data_directionary, exist_ok=True)
meta_iteras_list = list(range(59000, 60000, 1000))

all_start = time.time()

cos_acc_path = data_directionary + "cos_acc.json"
meta_sim_path = data_directionary + "meta_sim.json"
inner_sim_path = data_directionary + "inner_sim.json"
cos_acc = {}
meta_sim = {}
inner_sim = {}

model_start = time.time()
meta_iteras_cos_acc = []
meta_iteras_meta_sim = []
meta_iteras_inner_sim = []
print("load compare meta_iteration: 59000", "of model", model_names[0], "...", end=" ", flush=True)
start = time.time()




all_end = time.time()
print("All Calculation Time: " + sec_to_string(all_end - all_start), flush=True)

print("#################", flush=True)



load compare meta_iteration: 59000 of model RRAIL ... All Calculation Time: 00:00:00
#################


In [96]:
meta_iteration = analyse_utils.load_iter(59000, data_path="../new/")
last_meta_iteration = analyse_utils.load_iter(59000, data_path="../old/")

In [111]:
np.sum(meta_iteration["layer_output"]["layer_3"][:,0,0])

0.0

In [100]:
print(testx)

(100, 10, 800)


In [39]:
x=np.random.rand(10,100)
np.cov(x)

array([[ 0.08787571, -0.00385043, -0.00157987,  0.00178191,  0.00091015,
         0.0071103 , -0.01310886,  0.00420295, -0.00732999, -0.00307612],
       [-0.00385043,  0.08189283,  0.01856263, -0.01820026,  0.00481407,
         0.00576488, -0.00229006, -0.00217321, -0.00640936, -0.01482326],
       [-0.00157987,  0.01856263,  0.07768098, -0.01100492, -0.00773812,
         0.00934966, -0.0072017 , -0.00506935, -0.00606557, -0.02412066],
       [ 0.00178191, -0.01820026, -0.01100492,  0.08614289,  0.00208947,
         0.01063313, -0.00146467, -0.01437875, -0.00449412,  0.00915636],
       [ 0.00091015,  0.00481407, -0.00773812,  0.00208947,  0.08589681,
        -0.00561025, -0.00085525,  0.00513441, -0.00741052,  0.00299414],
       [ 0.0071103 ,  0.00576488,  0.00934966,  0.01063313, -0.00561025,
         0.07136882, -0.00159492, -0.00441764, -0.00251343,  0.00391502],
       [-0.01310886, -0.00229006, -0.0072017 , -0.00146467, -0.00085525,
        -0.00159492,  0.09261568,  0.00974914

In [ ]:
last_meta_iteration = analyse_utils.load_iter(59000, data_path=model_paths[0])

In [94]:
analyse_utils.calc_meta_sim(meta_iteration, last_meta_iteration,"pwcca",
                                                                          verbose=verbose,inner_loop_iters_list=[0,10])

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.04339664 0.04212892 0.05005075 ... 0.02194313 0.02497474 0.0239642 ]
 [0.06241773 0.06033713 0.07198845 ... 0.03953586 0.04499806 0.04317733]
 ...
 [0.25544906 0.2461507  0.25720546 ... 0.21005732 0.21978177 0.24738616]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
sigma_xx [[0.05894272 0.06186592 0.04789576 ... 0.06576625 0.00675874 0.03635812]
 [0.06186592 0.06641792 0.05035001 ... 0.07266277 0.00709047 0.03745228]
 [0.04789576 0.05035001 0.04365161 ... 0.05082736 0.00668369 0.03021269]
 ...
 [0.06576625 0.07266277 0.05082736 ... 0.0871253  0.00714766 0.03751906]
 [0.00675874 0.00709047 0.00668369 ... 0.00714766 0.00214995 0.00447797]
 [0.03635812 0.03745228 0.03021269 ... 0.03751906 0.00447797 0.05981009]]
sigma_xx [[ 0.03032388 -0.00466656 -0.01831751 ...  0.00408242 -0.02054658
  -0.00063797]
 [-0.00466656

[{'layerwise': {'layer_0': 0.9762370724775613,
   'layer_1': 0.8871222427042937,
   'layer_2': 0.7508867597062105,
   'layer_3': 0.6859982522573811,
   'layer_4': 0.5364522898223101},
  'iteration': 0},
 {'layerwise': {'layer_0': 0.8336219106826992,
   'layer_1': 0.7421454719768592,
   'layer_2': 0.6803643235116303,
   'layer_3': 0.5975969758653934,
   'layer_4': 0.676661939703016},
  'iteration': 10}]

In [40]:
print(last_meta_iteration["layer_output"]["layer_0"][:,:,0].shape)

(100, 11, 20, 14, 14, 64)


In [114]:

importlib.reload(pwcca)
importlib.reload(cca_core)
importlib.reload(analyse_utils)


analyse_utils.calc_meta_sim(meta_iteration, last_meta_iteration,"pwcca",layers=["layer_0"],
                                                                          verbose=True,inner_loop_iters_list=[0])

fast identisch
innerloop iteration 0 {'layerwise': {'layer_0': 1}}


[{'layerwise': {'layer_0': 1}, 'iteration': 0}]

In [113]:
testx=last_meta_iteration["layer_output"]["layer_0"][:,0,0].mean(axis=(2,3)).reshape((2000,64)).T

ValueError: cannot reshape array of size 32000 into shape (2000,64)

In [89]:
pwcca.compute_pwcca(testx, testx, epsilon=1e-9)[0]

sigma_xx [[0.05894272 0.06186592 0.04789576 ... 0.06576625 0.00675874 0.03635812]
 [0.06186592 0.06641792 0.05035001 ... 0.07266277 0.00709047 0.03745228]
 [0.04789576 0.05035001 0.04365161 ... 0.05082736 0.00668369 0.03021269]
 ...
 [0.06576625 0.07266277 0.05082736 ... 0.0871253  0.00714766 0.03751906]
 [0.00675874 0.00709047 0.00668369 ... 0.00714766 0.00214995 0.00447797]
 [0.03635812 0.03745228 0.03021269 ... 0.03751906 0.00447797 0.05981009]]


0.9997458730317562

In [4]:
import numpy as np

In [6]:
np.zeros((1,2,3)).shape==np.zeros((1,2,4)).shape

False